language: java
jdk: oraclejdk11

after_deploy:
  - echo "done deploying"
  
  
env:  
	global:  
	- secure: "Yp0z3YbNCtDqualqYYDddVVVlVR7hhw5hY3PwZleYzGUYBQ9Z/Bux+hZsLBIelm6FL+A06arrBpnIj432OyzgiYyOXBp61JmKNqrkKda9vM9xkuf/qBrwlRyxjBq+yuIISJsvNxDIK5i7hEdWcylCiywoS0Vv3HZvxjDlnmzFYSFVEvRTUXkyCHFc0Na+yPb9G0Ajc3qCmZTaNUat1BOGDA1D80KPDQo4lTDdTpYiboVo5yPaTHe7sPdFmE0l8EkqLK9krq+GTeEDf9/yimMowfISkmFy1k/kjmGWszIuNsxHE+spJe/OZFA4JKm1hZ77Mq/AE45YfcEgvbO/pkKRdRW6gb5h8x4l9WMXetS9tf6d2m3jIByQ59K1n/x2FUr2x52crsC+Zt/A0K2uqGcTFvgVRxlKDiUZESXO9KuMyHFVR84qR66xgz563LGVcDlkHhUwUnh0Iq5T30KRyAj42PaP4waRYrept1O4Mhr1j5G/4nHOjMwi+YIFjhXBGvA+X8J9vg1IBJMjhjFEOVkriJfGVUM6ENd0z6AekRPCcaSKzGc7E0Qqro7wu/TUSLXufVQau8hTYKu7NctwL7H6k6BAmIj9vr1hNIaYpZlu5CvGQqK5zIGCHys0KweHgO9seu6CIEdHDqwUq8AjznJ92VYIGC/x+3rbqouft0Ouho="
